### ISSUE TITLE
move linhguinii.md to first-contributions/linhguinii.md

### ISSUE THREAD

**Issue by Subskii** [the-fast-tracked-programmer/first-contributions#63]
fixes #36 

missed this in the initial review @Linhguinii. Oops!

Great practice for follow up :)

**Comment by Subskii** [comment]
```
/first-contributions$ git mv linhguinii.md first-contributions/linhguinii.md
/first-contributions$ git commit -m "move linhguinii.md to first-contributions/linhguinii.md"
```

**Comment by Subskii** [comment]
oh @Linhguinii you're going to hate me! :sweat_smile: 

It looks in pull request #71 the file was copied to the [right place](https://github.com/the-fast-tracked-programmer/first-contributions/blob/main/first-contributions/linhguinii.md), not moved... sorry I didn't notice that when reviewing!

Last thing left to do is open a pull request which deletes [this file](https://github.com/the-fast-tracked-programmer/first-contributions/blob/main/linhguinii.md), and `closes #36` (this issue).

Then we'll be done!

**Comment by Linhguinii** [comment]
No worries haha

That's weird because on my computer there's no linhguinii.md on the main directory.

**Comment by Subskii** [comment]
> That's weird because on my computer there's no linhguinii.md on the main directory.

Great observation there.

Thinking you'll need to fetch upstream from your forked repo

![fetch-upstream](https://user-images.githubusercontent.com/394074/132317154-ec1df73f-27a5-4472-9513-29dcf0f862e6.jpg)

pull the changes in locally with `git pull`

then create a branch that removes the original file, and open a new pull request.

Any issues just let me know.
